name: default
channels:
  - pyviz
  - defaults
dependencies:
  - python=3.9.7
  - colorcet=3.0.0
  - datashader=0.13.0
  - geoviews=1.9.3
  - holoviews=1.14.7
  - hvplot=0.7.3
  - panel=0.12.6
  - jinja2<3
platforms:
  - linux-64
  - osx-64
